### ISSUE TITLE
Allow Accumulate and type system generation/validation refer to external typed nodes

### ISSUE THREAD

**Issue by willscott** [ipld/go-ipld-prime#114]
If one has a custom implementation of a node type, there's no graceful way to use that with a typegen'd type system. This could be as simple as somehow marking "don't generate the type and implementation for this type", or ideally by being able to say the type exists already and then substitute a language-appropriate reference at the time of language-specific code generation.

**Comment by warpfork** [comment]
https://github.com/ipld/go-ipld-prime/pull/116 means this is now accomplishable (if hackily), yes?
