### ISSUE TITLE
Constant for common selectors

### ISSUE THREAD

**Issue by willscott** [ipld/go-ipld-prime#171]
There is currently no way to easily get an `ipld.Node` version of a selector representing "give me the whole dag".
This is a very common request, and that it involves something like
```
	ssb := builder.NewSelectorSpecBuilder(basicnode.Prototype__Any{})
	ss := ssb.ExploreRecursive(selector.RecursionLimitNone(), ssb.ExploreUnion(
		ssb.Matcher(),
		ssb.ExploreAll(ssb.ExploreRecursiveEdge()),
	))
	ss.Node()
```
but there isn't documentation or examples of that anywhere leads to a lot of confusion.

**Comment by ribasushi** [comment]
@willscott @mvdan fwiw markets does put it behind a const-like function: https://pkg.go.dev/github.com/filecoin-project/go-fil-markets/shared#AllSelector

**Comment by ribasushi** [comment]
@willscott ... and it is **different** from your example... confusing 🤔

**Comment by willscott** [comment]
the difference is if you want to 'match' all nodes, or just 'cover' all nodes

see https://github.com/ipld/go-ipld-prime/blob/master/traversal/selector/matcher.go#L9-L18

**Comment by rvagg** [comment]
What's the practical difference between these two operations? matching vs covering? I don't grok the difference in how you'd consume these things as distinct operations. It seems to me that the `AllSelector` version is doing a dag walk, while the `ExploreUnion` + `Matcher` is ... addressing the entire dag? What are the usage patterns that make this distinction helpful?

**Comment by willscott** [comment]
I think the proof of "i did the walk to search for _x_" is the covering,
and the actually returned things are the matching subset.

**Comment by ribasushi** [comment]
@willscott just checking in case I missed a thread elsewhere: has here been any movement on this?

**Comment by willscott** [comment]
@ribasushi there is: it's in https://github.com/ipld/go-ipld-prime/pull/199

**Comment by mvdan** [comment]
I'd love it if we could get this over the finish line :) Another person is struggling to use go-car with selector nodes: https://github.com/ipld/go-ipld-adl-hamt/issues/24#issuecomment-884042499

**Comment by warpfork** [comment]
https://github.com/ipld/go-ipld-prime/pull/199 did introduce some of these, and is now merged, so I think this can be marked closed as a success.
