### ISSUE TITLE
provide a standard way to compare Nodes for equality

### ISSUE THREAD

**Issue by mvdan** [ipld/go-ipld-prime#173]
Right now we only have one ipld.Node implementation: it's code-generated via `schema/gen/go`, and it's assumed by default that we can use `reflect.DeepEqual` on it. Some of the tests do this, such as when doing a codec encode-decode roundtrip and checking that the node looks the same.

However, this breaks down with other Node implementations. Here are two examples:

1) ADLs, where the Go value could be... anything. Moreover, if two ADLs behave like nodes with different kinds, but their Go values happen to be the same, should they really be considered equal nodes? I imagine not.

2) Nodes built via reflection, as per https://github.com/ipld/go-ipld-prime/pull/170. Since those "wrapper" Go values also include a reference to the IPLD schema, and schemas can be cyclic... DeepEqual panics.

I think the only reasonable solution to this is to define a high-level `ipld.DeepEqual` function, which is similar to `reflect.DeepEqual`, but works on IPLD kinds and values instead. For example, a basic IPLD string "foo" and a fancy custom-built ADL whose kind is string and whose AsString returns "foo", would be equal as far as this API is concerned.

I don't think it would be necessary to support options for this API. If we really think we'd need options, I think we should either rely on the traversal APIs for this, or reuse the existing semi-standard [go-cmp](https://pkg.go.dev/github.com/google/go-cmp/cmp#Options).

I discarded an optional `Equal(ipld.Node) bool` method on nodes because this would be repetitive, likely inconsistent, and could result in weirdness like `a.Equal(b) == true && b.Equal(a) == false`. Some Go APIs like crypto/... went this route, but note that they are a single implementation forever, so they are always dealing with just one non-interface type.

cc @warpfork @willscott @hannahhoward

**Comment by mvdan** [comment]
I'm open to better names, by the way. The behavior would essentially be:

* kinds match
* if the kind is scalar, the values must be equal as per Go's `==` operator
* if the kind is recursive (maps, lists, ...), the values must be recursively equal as per the rules above

So maybe `ipld.KindDeepEqual` if we want to make it very clear that this is all around how a node represents itself via the IPLD interface, and not its underlying Go value or type.

**Comment by willscott** [comment]
`DeepEqual` seems like a reasonable addition to me

**Comment by warpfork** [comment]
sounds perfect.

**Comment by mvdan** [comment]
Cool, I'll probably do this as part of my IPLD schema+node test refactor next week, because otherwise I can't use the tests with the reflection implementation.
