### ISSUE TITLE
document that ListIterator.Next must return 0..Length-1 indexes

### ISSUE THREAD

**Issue by mvdan** [ipld/go-ipld-prime#175]
Many parts of IPLD assume the ListIterator indexes will start at 0, and increase one by one until Length-1 is reached (i.e. Done).

Potentially we could consider supporting iterators that produce elements out of order, such as producing a list out of a data structure that doesn't keep all elements in order in an efficient way. However, that's just a thought experiment at this point.

We should document that the index result parameter is, at this point, just a convenience. Anyone who just wants to do the equivalent of `for _, elem := range ...` can just ignore the indexes and assume they are always equal to `for i, elem := range ...`.

cc @warpfork @willscott

**Comment by warpfork** [comment]
Good news; we did already say this on the `ListIterator` interface's docs:

> // A loop which iterates from 0 to Node.Length is a valid
> // alternative to using a ListIterator.

But still agree that this could be clearer.  I will draft some more docs that increase explicitness and repeat it in more discoverable places.
