### ISSUE TITLE
schema: add TypedPrototype

### ISSUE THREAD

**Issue by mvdan** [ipld/go-ipld-prime#181]
Right now we have a `schema.TypedNode`: https://pkg.go.dev/github.com/ipld/go-ipld-prime@v0.9.0/schema#TypedNode

It's the same as an `ipld.Node`, but with the extra methods `Type() Type` and `Representation() ipld.Node`. Any IPLD node that corresponds to an IPLD schema should have both of these available.

This works fine when using IPLD nodes, but not when constructing IPLD nodes; we don't have anything like a `TypedPrototype`. I needed that interface in the new bindnode package, so I temporarily declared it there:

https://github.com/ipld/go-ipld-prime/blob/064087509c831ae61a7187f7128a4fafe3c84657/node/bindnode/node.go#L182-L186

Before we stabilize bindnode's API, I'd really like to move that interface to a better place, like the schema package. Note that my interface doesn't have `Type() Type`, but it probably should include that in the schema package for consistency with `TypedNode`.

The benefit here is clear: if I have a prototype for a schema, there's no way to directly get the prototype for its representation. I'd need some external way to get to it. This is used for the schema tests in bindnode for example; `PrototypeOnlySchema` just gives one prototype, so there would be no way to get to the representation prototype otherwise. If we define this interface, the bindnode APIs could start returning a `TypedPrototype` instead of just `NodePrototype`, which would also make the API more useful.

The existing codegen sidesteps this issue by exposing both regular and repr prototypes globally, such as in the dagpb link below. However, I argue that's a symptom of the lack of `TypedPrototype`; codegen could expose just the regular prototype, with a method to get its representation prototype.

https://github.com/ipld/go-codec-dagpb/blob/v1.2.0/ipldsch_types.go#L28-L33

I guess the name `TypedNodePrototype` would be more consistent and explicit, but I personally find it too long. `TypedPrototype` is unambiguous and easy to remember.

cc @warpfork @hannahhoward @willscott

**Comment by warpfork** [comment]
Yep, agree, this should exist.  It seems like a natural arrow to have in completing the graph of transitions.

I don't think there's a good reason or any Chesterton's Fence for why this type doesn't exist yet.  Just good ol' oversight.
