### ISSUE TITLE
Potential issues with generated union types

### ISSUE THREAD

**Issue by i-norden** [ipld/go-ipld-prime#201]
It's been a pleasure working with the new schema tools, node type, and assemblers! They're powerful, once you get the hang of the new patterns it becomes very straight forward and ergonomic to generate complicated types and write their codecs.  

While working on and testing the [ethereum](https://github.com/vulcanize/go-codec-dageth) and [tendermint+cosmos](https://github.com/vulcanize/go-codec-dagcosmos) codec implementations we've uncovered some (potential) issues with generated union types, that we were able to resolve with some tweaks to the generated code. These could also be due to my misuse/misunderstanding.

1. Union representation types are generated (e.g. `_Child__Repr`) but not used by other generated types, they use the default representation (e.g.`_Child`) which are map keyed with the name of the types the Union can hold (probably just an issue with my expectations).

2. `AssembleValue()` switch statements for union assemblers (e.g. `_TrieNode__Assembler`) required some manual adjustments. The `ma.ca` cases are off by one, needed to be incremented ([example](https://github.com/vulcanize/go-codec-dageth/commit/a261be0b3de9ab0ee15af092eee02b514b7557d1#r53227256)).

3. Needed to manually change some union type and assembler fields to pointers to allow compilation of recursive types ([example](https://github.com/vulcanize/go-codec-dageth/commit/8adf54897ec6c038604b5c4ce2d2d3c3a7febdf1#r53228042), [example](https://github.com/vulcanize/go-codec-dageth/commit/8adf54897ec6c038604b5c4ce2d2d3c3a7febdf1#r53227444))

4. Related to the above, changing some of the fields to pointers introduced the need for some `nil` checks and zero value substitutions ([example](https://github.com/vulcanize/go-codec-dageth/commit/a261be0b3de9ab0ee15af092eee02b514b7557d1#r53227330)).

Would be happy to look into fixing these issue- if they are indeed issues- but want to make sure they are first.

**Comment by BigLep** [comment]
@i-norden : sorry this has languished.  Is this still relevant for you?  Is there any additional info?

**Comment by BigLep** [comment]
Resolving due to lack of input.  Feel free to reopen with more info.  In general we're not investing in codegen unless there are targeted specific things we can fix.
