### ISSUE TITLE
wishlist: port all tests to quicktest

### ISSUE THREAD

**Issue by warpfork** [ipld/go-ipld-prime#219]
https://pkg.go.dev/github.com/frankban/quicktest is now clearly superior to https://pkg.go.dev/github.com/warpfork/go-wish .

We've started using `quicktest` in some parts of this repo already and it's working great.

It would be nice to port all the tests to using `quicktest` and see one more dependency drop from the `go.mod` file.

This should be relatively easy.  The style used by `quicktest` and `wish` are syntactically and semantically extremely similar.

**Comment by mvdan** [comment]
I'd usually recommend to do a slow transition as the codebase is modified, to avoid too much churn and conflicts.

But in this case, given that go-wish and quicktest are pretty similar, it probably doesn't make sense to leave the repository using both for months or years. So maybe it is worth the effort to try to automate the refactor.

Maybe it could be done in groups of packages, to make the reviews less painful.
