### ISSUE TITLE
json decoder returns no error when decoding zero data

### ISSUE THREAD

**Issue by warpfork** [ipld/go-ipld-prime#230]
It should probably return some sort of EOF error in this case.

It is clearly an error condition, because if you call `nb.Build()` after this, it'll probably yell at you quite loudly, since the NodeBuilder also received no data, and thus is in an invalid state.

**Comment by mvdan** [comment]
Is this fixed by https://github.com/ipld/go-ipld-prime/pull/241, or is this a different edge case?

**Comment by warpfork** [comment]
Hm.  Probably?  There's still the [zero-bytes-is-different-than-some-bytes-that-are-invalid](https://github.com/ipld/go-ipld-prime/pull/241#issuecomment-913314455) distinction, which I wish we were able to be clearer about... but this issue doesn't talk about that exactly either, so, yeah, maybe we can just close it.

**Comment by mvdan** [comment]
That sounds like a new issue :)
