### ISSUE TITLE
API usage & Go noob question

### ISSUE THREAD

**Issue by rvagg** [ipld/go-ipld-prime#24]
Given a `val []byte` that's a dag-cbor encoded byte array, I want to decode it and fetch some basic fields from it:

```go
	root, err := dagcbor.Decoder(ipldfree.NodeBuilder(), bytes.NewReader(val))
	if err != nil {
		return err
	}
	hashAlg, err := root.TraverseField("hashAlg")
	if err != nil {
		return err
	}
	hashAlgS, err := hashAlg.AsString()
	if err != nil {
		return err
	}
	bitWidth, err := root.TraverseField("bitWidth")
	if err != nil {
		return err
	}
	bitWidthI, err := bitWidth.AsInt()
	if err != nil {
		return err
	}
	bucketSize, err := root.TraverseField("bucketSize")
	if err != nil {
		return err
	}
	bucketSizeI, err := bucketSize.AsInt()
	if err != nil {
		return err
	}
	data, err := root.TraverseField("data")
	if err != nil {
		return err
	}
	dataLength := data.Length()

	fmt.Printf("hashAlg=%s, bitWidth=%d, bucketSize=%d, elements=%d\n", hashAlgS, bitWidthI, bucketSizeI, dataLength)
```

Is this how I'm supposed to use it? Am I supposed to be OK with all of the `err` handling or are there some shortcuts I should be considering to collect this data?

**Comment by warpfork** [comment]
> Is this how I'm supposed to use it?

Yep!

---

> Am I supposed to be OK with all of the err handling or are there some shortcuts I should be considering to collect this data?

You can also check out using the `fluent` package: https://godoc.org/github.com/ipld/go-ipld-prime/fluent

That should shorten this up quite a bit:

```go
rootBare, err := dagcbor.Decoder(ipldfree.NodeBuilder(), bytes.NewReader(val))
if err != nil {
	return err
}
root := fluent.WrapNode(rootBare)
err = fluent.Recover(func() {
	data := root.TraverseField("data")
	fmt.Printf("hashAlg=%s, bitWidth=%d, bucketSize=%d, elements=%d\n",
		root.TraverseField("hashAlg").AsString(),
		root.TraverseField("bitWidth").AsInt(),
		root.TraverseField("bucketSize").AsInt(),
		data.Length(),
	)
})
```

You can also skip the `fluent.Recover` block if just banging something out; but any errors will then panic and halt your whole program.  Fine for hacking, doesn't hold up too far.  `fluent.Recover` takes all those sorts of errors and gathers them into one return value.  You can use the recovery blocks judiciously (and they nest just fine) to express different failure groups, or throw a giant one around a whole program just to pretty print the error.

(There's probably a *slight* perf penalty to using a fluent wrapping, but I haven't measured it yet, and wouldn't worry about it unless you're doing something you know is going to be a "hot path" -- and even then, it's easy enough to write something with fluent first, and do a type-safe compiler-guided refactor later with minimal effort.)

---

Also worth noting that in many cases we don't expect this interface to be the one end users encounter.  It's "plumbing".  Important, central plumbing; but plumbing nonetheless.

For example, 
- using `traversal` functions to either walk by path or by a Selector don't have to do error checking at each stride; they get it all at once.
- when doing schema-powered codegen, the generated code has accessor functions all the way through which don't have local error handling; all the error handling is frontloaded onto any parse stages and all in one place.  (n.b. yes, this is still a work in progress at the time of writing.)
- and so on.

Mostly it's us who're writing generic algorithms (such as graph traversals) who are exposed to this level of plumbing; and also, us who are writing stuff now before some other nicer interfaces are ready (e.g., a lot of the Selectors work used these plumbing interfaces; but later, we might actually be able to replace them with codegen; and I infer you're drafting up a HAMT here, and that might be in the same boat: might be easier to write later with codegen'd components (it's just that we don't necessarily want to wait around for that dependency)).

**Comment by warpfork** [comment]
Gonna close because I think that's the right thing to do with "question" issues on github and I wanna try to keep near to "inbox zero" :)  Hope this helped and reopen if not.
