### ISSUE TITLE
Cid.Undef IPLD de-serialization error

### ISSUE THREAD

**Issue by adlrocha** [ipld/go-ipld-prime#246]
If we use `cid.Undef` to create a new `datamodel.Link` with `cidLink`, it is serialized as `"/": "b"`, which means that when trying to de-serialize it, we get `cid is too short`. I don't think we should error in this case. We should probably not serialize `cid.Undef`, or use a `Null` type, to allow de-serialization in the other end. I don't know if this the expected behavior we wanted for `cid.Undef` or it is open to discussion.

### Background
I was serializing an IPLD node map with a bunch of links, some of them were `cid.Undef`, and I was getting `cid is too short`. I was blaming the Links which were actually set, when in the end it was the `cid.Undef` the one to blame.

**Comment by willscott** [comment]
Note that part of this duality is because of the quirk in how we represent `Cid`'s in Golang. Since they are strings, a primitive type, they cannot be 'nil', and so `Undef` gets commonly used for that 'not yet set' case that may represent either explicit Absentness or Null

**Comment by rvagg** [comment]
https://github.com/ipld/go-ipld-prime/pull/196 possibly helps with this?
