### ISSUE TITLE
consider: panic catchers around all codec usage?

### ISSUE THREAD

**Issue by warpfork** [ipld/go-ipld-prime#261]
Should we have `recover` blocks around usage of `codec.Encoder` and `codec.Decoder` functions, in order to put a limit to how far any panics might propagate from a buggy codec?

There's two places this would need to happen right now: the methods on `linking.LinkSystem`, and all the `Encode*|Decode*|Marshal*|Unmarshal*` helper functions in the root `ipld` package.

It should be noted that while it's possible to wrap our own known usages of codec functions, it is impossible to wrap _all_ usages of `codec.Encoder` and `codec.Decoder`.  They're interfaces -- anyone can implement them.  Also, some of our existing API surface area (for example, the multicodec registry) returns those function interfaces directly, so no wrapper is possible at those points.

**Comment by warpfork** [comment]
I'm unsure how I feel about this.  On the one hand, some defence-in-depth is sometimes useful.  On the other hand, I'm not actually sure how much more clarity or quality-of-life-during-debugging this can provide.

I'm also a little concerned that it might be confusing to end-users if we do this panic catching in _some_ places; we'd have to take care to document where we _don't_(/can't) do it.

On the other hand, considering that codecs are supposed to be easy to plug in, maybe their usage sites do deserve some more defense-in-depth than other API boundaries.

**Comment by BigLep** [comment]
2022-06-07 conversation: closing since we have effectively said this is the responsibility of higher levels in the stack (e.g., graphsync) and there hasn't been a pressing need to do it since.  We can revisit if this re-emerges.
