### ISSUE TITLE
node/bindnode: support for optional/nullable Links

### ISSUE THREAD

**Issue by adlrocha** [ipld/go-ipld-prime#306]
When setting a schema field of kind `Link` as `nullable/optional`, we persistently receive `optional types must be pointers` even when using pointers for `cid.Cid` in the schema-related struct. 

For instance, for the schema:
```go
ts.Accumulate(schema.SpawnStruct("CheckData",
        []schema.StructField{
                schema.SpawnStructField("Test", "Link", false, true),
        },
        schema.SpawnStructRepresentationMap(nil),
))
```
Bindnode fails when using the following struct:
```go
type CheckData struct {
        Test *cid.Cid
}
```
//cc @mvdan

**Comment by mvdan** [comment]
I am fairly confident that https://github.com/ipld/go-ipld-prime/commit/ac5b5fd4b203318fd5b0fbef13401be9c84e991f fixed this. We now verify that we can bind `Link`, `optional Link`, and `nullable Link` with all the combinations of `*cid.Cid`, `*datamodel.Link`, and `*cidlink.Link`.

If you update to the latest master and it still doesn't work, please let me know :)

**Comment by adlrocha** [comment]
@mvdan, sorry for the delay. It's definitely fixed. Thanks!
