### ISSUE TITLE
node/bindnode: plug the footgun that is using the repr-level enum strings in Go

### ISSUE THREAD

**Issue by mvdan** [ipld/go-ipld-prime#348]
A user ran into a bug in the form of:

```
type GraphSyncLinkAction enum {
   | Present             ("p")
   | Missing             ("m")
} representation string
```

then backed in Go by a string, like:

```
type LinkAction string
const (
	LinkActionPresent = LinkAction("p")
	LinkActionMissing = LinkAction("m")
)
```

This didn't work:

> AsString: "p" is not a valid member of enum GraphSyncLinkAction

The fix was to use the strings for the enum members at the type level, rather than the representation level, which is how bindnode works:

```
type LinkAction string
const (
	LinkActionPresent = LinkAction("Present")
	LinkActionMissing = LinkAction("Missing")
)
```

This is all working as intended, but the mistake is easy to make, and the error didn't really point the user in the right direction.

We should probably do something here like a better error message, such as:

> AsString: "p" is not a valid member of enum GraphSyncLinkAction (bindnode works at the type level; did you mean "Present"?)

**Comment by rvagg** [comment]
Genuine footgun, also hit in this commit (hence failing tests): https://github.com/ipld/go-ipld-prime/pull/350/commits/dfa7373f15dfc81027ecd0ce9760bc4befda2214
