### ISSUE TITLE
Patch MVP

### ISSUE THREAD

**Issue by BigLep** [ipld/go-ipld-prime#353]
## Goal
Make it clear that IPLD can do more than put/get.  The IPLD Patch system demonstrates the value of a coherent datamodel and the excellence of data-driven APIs (including operation over ADLs).

## Done state
At the end of this we will have:
- [x] Parsing patch operation messages (based on the JSON Patch RFC).
  - [x] add
  - [x] replace
  - [x] remove
  - [x] copy
  - [x] move
  - [x] test
- [x] Applying sequences of patches to a Node, which produces a new Node or error.
- [ ] Applying a sequence of patches to a Node, with changes crossing links, and creating multiple new blocks.
- [ ] Parsing patch+target requests (e.g. patch operations together with a CID to apply them on).
- [ ] Evaluating patch+target requests against a LinkSystem, and producing an updated CID.
- [ ] Tag a go-ipld-prime release which contains the new functionality.
- [ ] Update [docs](ipld.io/docs/intro/hello-world.md) to reflect that Patch is no longer "in development"

Stretch goals, which may be reached, but may need followup:
- [ ] Stretch: demonstrate patches applied to an ADL node.
- [ ] Double stretch: patch+target requests include ability to declaratively signal where to apply an ADL, and work from there alone.

(These goals are stretch goals because they are very likely to be acheived, or brought within sight of a finish line, by success of this design.  However, it also assumes other systems are also at a high level of doneness, which is not re-verified while drafting this plan; additionally, the full integrations of this are nontrival to test -- and those tests are considerably important, so we will not mark these fully done until having a good test harness and good robust fixture-driven tests for it.)

## Notes:
1. Performance is not a priority for this MVP.

## Why?
Enables a user to incrementally update data, in a practically unbounded way, with a declarative API.  In the absense of this, someone has to write code to load the data, write code to walk the data, more code to alter the data, lots of custom code to handle if things are too big or not the shape you expected (all of which will probably evolve in rancid ways over time). Lots of manual work.

IPLD Patch drives ADLs forward (perfect target: specifically drags forward the API for incremental updates that are performant).

It's also identity forging, with a clear demo that can be a public talk cornerstone.

## Potential usecases
When this is made fully robust, Ceramic could offer "Streams" that have a HAMT at their root, and scale infinitely as a result.

**Comment by BigLep** [comment]
@warpfork : I wasn't sure if Patch with ADL will be demonstrable with this as part of the MVP.  Feel free to adjust if I got that wrong.

**Comment by BigLep** [comment]
Legacy internal PL document that may have more useful information to extract: https://www.notion.so/protocollabs/IPLD-Patch-feature-dfccca423daf4ffc910df94a4195ba98

**Comment by BigLep** [comment]
@warpfork : these are the 6 operations to implement right?

- [ ] add
- [ ] remove
- [ ] replace
- [ ] copy
- [ ] move
- [ ] test

I put them in the issue description so they can cross off as we make progress here.

**Comment by warpfork** [comment]
The six basic operations are now all supported and tested, in https://github.com/ipld/go-ipld-prime/pull/350, and with matching specs and fixtures PR in https://github.com/ipld/ipld/pull/187.

**Comment by RangerMauve** [comment]
Picked this up. Spent some time reading up on the existing code this week.

Got the tests working and started addressing some concerns in pull request reviews.

After that my next steps will be patches which traverse Links. I think after tests pass for that the current state should be good enough to merge.
