### ISSUE TITLE
dagjson.Decode support for self-delimited reading

### ISSUE THREAD

**Issue by petar** [ipld/go-ipld-prime#374]
The current implementation of dagjson.Decode consumes whitespaces and EOF after a valid object.
This precludes repeated use on a single stream. Perhaps we could introduce a decoder option that does not consume any bytes after the terminal "}". This is generally the expected design for a decoder of any self-delimited format, in the sense that the self-delimitedness property is otherwise unusable in code. (E.g. json.Decode.)

**Comment by BigLep** [comment]
2022-05-03 triage conversation: this isn't something we're going to build into the core.  This would need to be a special mode.  Contributions welcome.
