### ISSUE TITLE
dag-cbor How do I get (dagjson.Encode(n, os.Stdout)) printed data?

### ISSUE THREAD

**Issue by Junqiang-Zhu** [ipld/go-ipld-prime#439]
How do I get this data?

![微信截图_20220614114704](https://user-images.githubusercontent.com/89182300/173489346-6c7ef5bc-9824-4dd0-830b-208927a60618.png)

**Comment by rvagg** [comment]
`dagjson.Encode(node, os.Stdout)` is sending the output to an `io.Writer`, in this case, `os.Stdout`. Make your own `Writer`, or use a `bytes.Buffer` which can act as a `Writer` to capture it.

What may work better is to use the top-level codec helpers - have a look at https://pkg.go.dev/github.com/ipld/go-ipld-prime#Encode - which will return `[]byte`, and you just need to pass it `dagjson.Encode` as the "encoder" argument.

I hope that helps.

**Comment by Junqiang-Zhu** [comment]
thank you
