### ISSUE TITLE
Inline union representation in parser

### ISSUE THREAD

**Issue by simonwo** [ipld/go-ipld-prime#481]
Hi, I've just been trying to use an IPLD Schema (and making great progress so far!) and have just run into a TODO around inline unions:

https://github.com/ipld/go-ipld-prime/blob/61c9ab10d42aa5007ea3594cf90bce738b91246e/schema/dsl/parse.go#L646

My context is that I am doing a first pass at implementing the [UCAN Invocation spec](https://github.com/ucan-wg/invocation/pull/1) which uses an IPLD Schema.

In UCAN Invocation, there are multiple `Task` types with a similar set of keys, and I want to use an inline union to represent the types that [Bacalhau](https://github.com/filecoin-project/bacalhau) can support so that the parser can automatically pick out the correct type for the strongly-typed-per-task `Inputs` key, e.g.:

```ipldsch
type Task union {
    | DockerTask "docker/run"
    | WASITask "wasm32-wasi/run"
    | NoopTask "noop"
} representation inline {
    discriminantTag "do"
}

type DockerTask struct {
    With Resource
    Inputs DockerInputs
    Meta {String:Config}
}

type WASITask struct {
    With Resource
    Inputs WASIInputs
    Meta {String:Config}
}
```

I'd be happy to contribute some time to implementing this in the parser. Any objections to me going ahead and doing that? Is support elsewhere in the code for inline unions already present?

**Comment by rvagg** [comment]
@simonwo no objections moving ahead with any of this if you want to contribute! If it's just the parser you need to work then it shouldn't be too hard. There should be fixtures for it that you can pull in, hopefully it's obvious how those work and how the ones that are not implemented here are kind of commented out. I'm using it in JS here: https://github.com/ipld/js-ipld-schema/blob/master/test/fixtures/bulk/union-inline.yml but I think it's still in the ipld/ipld submodule linked to this repo but renamed so it's essentially commented out. It would need to be renamed and then made to work.

**Comment by BigLep** [comment]
@simonwo : Do you still need this?  If so, just curious if you've had a chance to create a PR for this?  Maintainers would be happy to look at it.

**Comment by delaneyj** [comment]
@BigLep I mentioned this in #475, would like to see fully support of unions.

**Comment by rvagg** [comment]
Decided to have a go at this https://github.com/ipld/go-ipld-prime/pull/527

**Comment by rvagg** [comment]
got my git commit metadata wrong, https://github.com/ipld/go-ipld-prime/pull/527 was supposed to close this and is merged now
