### ISSUE TITLE
bindnode panics if unable to infer type

### ISSUE THREAD

**Issue by hacdias** [ipld/go-ipld-prime#485]
The inferSchema function panics in multiple places if it's not able to infer the type of the binding object. I think it would be more reasonable to simply return an error, instead of panicking. It would be more clear to the user and more actionable. If this code is run without a recover, the program is killed.

https://github.com/ipld/go-ipld-prime/blob/b63657562d038d7cbfc32368ea0ab7d18ca77e02/node/bindnode/infer.go#L487

https://github.com/ipld/go-ipld-prime/blob/b63657562d038d7cbfc32368ea0ab7d18ca77e02/node/bindnode/infer.go#L485

**Comment by rvagg** [comment]
A lot of this setup stuff is typically done in `init` anyway, where you really need it to work properly first time. Arguably this is programmer error, not runtime error so a panic is not unreasonable in that case. If you're supplying a type that can't be used then there's not much an error is going to be able to do.

But also, infer is pretty rough, you really should be coupling with a schema, the limits of what can be inferred are pretty tight.

There are a lot of panics in bindnode which I'm not super jazzed about, but this is not a place I'm too worried about—you should be catching this kind of thing during dev, it's like breaking the typing system.

**Comment by hacdias** [comment]
Interesting. I understand your point, and I just come to you with a user perspective. I was expecting that, just like `json.Unmarshal` (and others), I could just feed it a `map[string]interface{}` and it would be able to infer the types from there on, but it panics.

**Comment by rvagg** [comment]
Fair, but if you're looking for untyped decoding then you just want the basicnode interface; bindnode is for strong typing, typically where you have a schema to adhere to. https://pkg.go.dev/github.com/ipld/go-ipld-prime#Decode would be enough for that. Then you have to wrestle with the `Node` interface, which may not be as nice as a `map[string]interface{}` but allows all of the other IPLD superpowers to be built on it. No plain `map` interface _yet_.
