### ISSUE TITLE
is there a rust version of this project ?

### ISSUE THREAD

**Issue by hunjixin** [ipld/go-ipld-prime#57]

**Comment by vmx** [comment]
There are several IPLD efforts in Rust, I'd say most notable are:

 - https://github.com/ipfs-rust/rust-ipld That is the one I'm currently contributing to.
 - https://github.com/datalove-app/ipld This one has some code for schemas and selectors (but doesn't build atm).

**Comment by hunjixin** [comment]
@vmx will rust-ipld support .car format file

**Comment by vmx** [comment]
@hunjixin I'm not aware that anyone is working on that at the moment. It also doesn't need to be at it's core. Having something that car read/write .car files would be some external library, which would be built on top of rust-ipld.

**Comment by vmx** [comment]
@hunjixin I just found https://github.com/ChainSafe/forest/tree/a326fec9da75e75da8b254bf6da7b26541099bd4/ipld/car I don't know how complete that is, but it would at least be a starting point in regards to .car files.

**Comment by rvagg** [comment]
That looks close to complete to me, the only thing it'll probably fail on is v0 CIDs but that wouldn't be hard to fix, and maybe that can be deferred anyway if v0 CIDs are avoided.
