### ISSUE TITLE
Road to self-hosting schema types, and codegen CLI

### ISSUE THREAD

**Issue by warpfork** [ipld/go-ipld-prime#84]
This is an issue to round up the steps still needed to get fully self-hosting schema types in go-ipld-prime (e.g., codegen types from the schema-schema and have that generated code also control the whole info flow that powers codegen)... and thereafter, make a usable codegen CLI tool which can take IPLD Schema documents and get directly to business.  (The latter is dependent on the former, as we'll see.)

0. Resolve schema-schema alteration discussion; or, add codegen support for inline unions.
    - Existing discussion the possibility of schema-schema alterations at https://github.com/ipld/specs/pull/291
    - It may also be necessary to finish the codegen features for supporting "implicits" (but we might also be fine hacking around that for a first demo, and returning to it later).
    - It may also be necessary to include generating some types in the schema-schema which describe ADLs (but it's quite likely we can hack around that for a first demo and for the full self-host (since the schema-schema doesn't use any ADLs!), and return to it later).
1. Use codegen to produce types matching the schema-schema.  Manually -- using the  "[tmpBuilders](https://github.com/ipld/go-ipld-prime/blob/350032422383277e6545b9b1a49112123b5c43fb/schema/tmpBuilders.go)" functions to programmatically drive codegen.
    - Existing draft in the [schemaschema_test.go demo](https://github.com/ipld/go-ipld-prime/blob/350032422383277e6545b9b1a49112123b5c43fb/schema/gen/go/_demo/omg-schemas/schemaschema_test.go).
2. _Pause for inspection of the results._
    - Is this satisfactory?  Are there more helper methods missing?  Do we at least expect a lack of major shake-ups to this, before we go forward?
    - Do we want to revisit the output file organization at this time?  We're going to commit this stuff soon -- it's desirable if we minimize the diffs we'll be having in the future.
3. These codegen outputs now go in the `schema/dmt` directory.  They understand the Data Model Tree structure (thus the short name, "dmt").  They can parse the schema-schema JSON!
    - This means it is not necessary to directly rig an IPLD Schema DSL parser into this.  The DSL parser can be a separate process which produces JSON, which we can load with the DMT types.  Very convenient isolation of concerns.
4. Re-implement all the golang types that match the `schema.Type` interface to use the `dmt.*` generated types to store most of their information.  Create a function `Reify(dmt.Schema) -> schema.Typesystem`.
    - We'll still want two layers of golang types here, because the `dmt.*` types necessarily use `TypeName` *strings* (because cycles aren't possible in documents), whereas the reified golang types will add a bunch of methods which return *pointers* to other type info.
        - I think this'll end up looking roughly like e.g. `type TypeStruct struct { ts schema.TypeSystem, dmt dmt.TypeStruct }` -- the former field gives the power to look up other reified type info pointers, the latter contains the bulk of the data for this type.
    - This `Reify` function also does the cycle-checking and completeness-of-reference checking on TypeNames.
        - Therefore, there's a nice boundary marked by the go types: if it's a `schema.Type`, it's passed `Reify` and its checks; if it's a `schema/dmt.*` value, it's raw data that perhaps hasn't yet.
5. Make a CLI tool!  :tada: 
    - Because we have the nice logical pipeline of using the `schema/dmt` types to parse schema data, and then validate and reify those into the types that drive codegen, this is now "easy".
6. Delete all the "tmpBuilders" code.  Replace the bootstrap schema-schema gen file that used them with an invokation of the CLI tool instead!
    - I expect that parsing a document via the `dmt.*` types is going to be the main way to interact with schema type info the majority of the time.
    - If we do want to keep around programmatic builder methods: they should still probably be reattached to the `dmt.*` types.  (The programmatic builder methods have the same issues about cycles as the serial format itself does -- you have to use type name strings in the programmatic builder methods so that cycles are discussable -- so they're a lot more isomorphic to the `dmt.*` types than the reified ones.)

This is a fairly short list ;)

Most of the hold-ups are around increasing confidence in the components we already have built before we leap into self-hosting on them.  But we can choose where on the cautious/eager spectrum we want to be with that, I suppose.  The only costs that are long term to eager attempts are git repo bloat in case of extremely large diffs in the generated outputs over time, and that's... survivable.  (Also, opportunity cost of hacking on this vs all the other specs and etc work that's important right now; but that's another matter.)

There's also one possibly significant sidequest way back up at step 0 -- if we don't adopt the switch of schema-schema to use keyed unions for type declarations, we'll have to implement the codegen support for inline unions.  Inline unions are one of the handful of things not yet supported in codegen, and are a bit tricky at that.

---

There's at least one more sizable design decision that needs to be made and is closely related to this: how should codegen outputs implement the `schema.Type` values that describe them?

The two major options are:

- generate new, concrete golang types for each type in the schema;
- or: create the type info value the same way as the CLI does: use the `dmt.*` types to parse a JSON document (!), and simply embed the relevant json in the codegen output files.

Generating new concrete golang types for each instance of the type info means we can make access to that info very fast; and means the type info type and the NodePrototype type can be the same, which is very pleasingly parsimonious.  However, it may increase binary and GSLOC size of codegen packages.  It also means we'll have to make _interfaces_ for all the types like `schema.TypeStruct`, in addition to concrete types, and then those interfaces will be provided by both these generated types and the types which are used when handling reified type info but not codegen'd.

Going the embed-json-and-parse route would imply some computations on package init, which might be questionable (in sufficiently short-lived programs, I could see this being undesirable).  It also would mean we'd have to generate NodePrototype types for each schema type separately from the `schema.Type` info values.  It might result in smaller GSLOC (but... we'd probably need to measure that).  It would let us leave `schema.TypeStruct` and friends as concrete types, though, for whatever that's worth.

(I think I just talked myself into the gen choice by typing out this description of the tradeoffs.)

---

Bonus quests:

99. Replace the current hand-rolled `AdjunctConfig` with a short schema and codegen cycle of its own.  (It also deals with serializable config; might as well use our tools for it.)
    - This will be pretty necessary for the CLI tool to be _usable_ in practice, but can come on the second pass.  Demos can be made without it, at least.

**Comment by rvagg** [comment]
`ipld-schema to-json schema.ipldsch > schema.json` works on current schema-schema and can be adapted to the changes being made there, so that should help with bootstrapping this at least.

**Comment by warpfork** [comment]
Yep, I'm 100% counting on that.  Having a freestanding {schemaDSL}->{DMT(json)} transpiler is a really nice separation of concerns.

**Comment by warpfork** [comment]
... okay, phew, this issue described way too much work at once.  It also over-fixated on using codegen for the self-hosting of the schema information flows, which due to other developments since I first opened this (e.g. `bindnode`), we're no longer locked into.

I think most of these topics can now be redirected:

- 0, 1, 2 -- forget about it.  Those were codegen detail fixations.
- 3, 4, and 6 -- those are tracked by #188 now.
- 5 -- there's not a new issue for this yet, but we should make one, to focus in on the CLI wish, independent of the rest of this stuff.  (And it's not clear if that's going to be in the hotpath for any self-hosting.)
- "how should codegen outputs implement `schema.Type`" -> also going to be decided predominantly by #188.

**Comment by mvdan** [comment]
@warpfork this space has advanced significantly recently, so I think it's due for an update :)

**Comment by mvdan** [comment]
> 5 -- there's not a new issue for this yet, but we should make one, to focus in on the CLI wish, independent of the rest of this stuff. (And it's not clear if that's going to be in the hotpath for any self-hosting.)

I think this is now a separate repo: https://github.com/ipld/go-ipldtool

All the other items are either fixed or "forget about it", so I think we should close this umbrella issue - it has outlived its usefulness. The schema parser and compiler in Go aren't complete yet, but they're close.

**Comment by warpfork** [comment]
Agreed!  Thank you for housecleaning.
