### ISSUE TITLE
No way to learn destination type from a LinkReference

### ISSUE THREAD

**Issue by willscott** [ipld/go-ipld-prime#90]
schema allows a `SpawnLinkReference` e.g. [1](https://github.com/ipld/go-ipld-adl-hamt/blob/master/_regen/gen_test.go#L76). However, the codegen has to way to extract the referenced type from the link node. It would be useful, when traversing or otherwise engaging with a dag containing link references to be able to learn the prototype of the link's destination from the link `Node`.

**Comment by willscott** [comment]
The workaround for this lack ends up being duplication of code, of the form found in https://github.com/filecoin-project/statediff/blob/1e917e5095931ca1811c83712e502f81ab4460a0/transform.go#L163-L210

Would be great if this could be inferred from codegen somehow.

**Comment by warpfork** [comment]
There's a feature detection interface in the `schema` package that can be used for this:

```
type TypedLinkNode interface {
	LinkTargetNodePrototype() ipld.NodePrototype
}
```

... looks like codegen doesn't currently emit methods that match this though.  So that's needed.

**Comment by willscott** [comment]
Similar to this (happy to file as a separate issue), is there a way to learn the value prototype of a Map or List prototype?
